import './bodyFunction.css';
import Search from '../../Assets/Search.svg';
import Select from '../../Assets/Select.svg';
import Standout from '../../Assets/Standout.svg';

const Bodyfunction = () => { 
    return (
        <div className="bodyfunction">
            <div className="bodyfunction_element">
                <img src={Search} alt="Search"></img>
                <div className="bodyfunction_element_head">Search</div>
                <div className="bodyfunction_element_text">
                    Simply add a keyword or a term related to your business in the slogan maker search box. Wait for the magic to happen.
                </div>
            </div>
            <div className="bodyfunction_element">
                <img src={Select} alt="Search"></img>
                <div className="bodyfunction_element_head">Select</div>
                <div className="bodyfunction_element_text">
                    Choose from thousands of options generated by the slogan maker that fit your needs.
                </div>
            </div>
            <div className="bodyfunction_element">
                <img src={Standout} alt="Search"></img>
                <div className="bodyfunction_element_head">Stand Out</div>
                <div className="bodyfunction_element_text">
                    Congrats on your new slogan. It's time to win the world!
                </div>
            </div>
        </div>
    )
}

export default Bodyfunction;